### ISSUE TITLE
Create templates/typification for issue to make contributions easier

### ISSUE THREAD

**Issue by diego7marques** [global-aws-community/aws-ug-cookbook#14]
We should create templates for issues. It helps users to write more complete and robust issues/feature requests providing a set of questions as starting point.

Doc Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Example from [KEDA repo](https://github.com/kedacore/keda/issues/new/choose):

![image](https://github.com/user-attachments/assets/33554a70-c61f-490d-8151-50019a69b6e5)

**Comment by diego7marques** [comment]
@tigpt, I've created the PR #15 to address this topic. I tried to adapt the naming conventions from the example to something more related to our scenario, for example, from feature request to content request. Let me know what you think about that. 

I did two categories to start:
* Report an error 🚨
* Content request 📝

The configuration also allows blank issues in case none of the template fits.

As soon as you approve the PR, the templates will be available to everyone who try to create a new issue.

**🚨🚨 Before approving the PR, you should create the labels:  needs-discussion, feature-request and bug. 🚨🚨**  (sorry for the extra work 😅 )

**Comment by tigpt** [comment]
It was missing a generic issue template, fixed by @diego7marques on https://github.com/global-aws-community/aws-ug-cookbook/pull/18
