### ISSUE TITLE
Review landing page to make it more readable

### ISSUE THREAD

**Issue by diego7marques** [global-aws-community/aws-ug-cookbook#16]
The [homepage](https://github.com/global-aws-community/aws-ug-cookbook/blob/main/README.md) of the repo is a bit scarier (halloween mood 👻) and can make the impression of an exhausting page to read due to the number of topics and content available there.

Maybe reorganize the repo to a more partitioned way can be good to ensure engagement of new members. 

Suggestions I can think of:
* Keep a maximum of 5 topics in the landing page (only the core)
* Add a summary (like the current table of content) that redirects the user to an page exclusively created to that topic

Few references: 
* https://www.hatica.io/blog/best-practices-for-github-readme/
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

@tigpt @encinar would love to have ideas/comments on this one, to hear your perception as well, as it can be a key for success in terms of engagement.

**Comment by tigpt** [comment]
solved by the PR 24 mentioned above
