### ISSUE TITLE
Repo Logo

### ISSUE THREAD

**Issue by tigpt** [global-aws-community/aws-ug-cookbook#25]
Lets make a logo for the repo to give it more life

**Comment by tigpt** [comment]
We got inclined for the fridge, some more drafts
![cooking book mascot 2](https://github.com/user-attachments/assets/78cba8f5-5904-4e4c-8c22-e0964727d64e)

**Comment by tigpt** [comment]
Why a fridge? Because on this repo you have plenty of options of content for you to consume.
- Theres the quick snacks on the door
- The ready to go meals that you can quickly warmup
- The raw ingreedinents that you can use to create your own recepie
- As well as the frozen trues, the ones you don't touch in months or years, but its good to look at them every once in a while.

![cooking book mascot 2 draft](https://github.com/user-attachments/assets/10b5c20a-d2c3-4838-b15e-d6bb95f4f35e)

**Comment by diego7marques** [comment]
v1 of the logo is available: 
![cookbook mascot test](https://github.com/user-attachments/assets/48fc99f2-efd8-43ab-8465-835a667f6352)


The next step will be to color and make minor adjustments.

**Comment by tigpt** [comment]
New version with User Group magnet letters on the fridge.

![cookbook_mascot_alpha](https://github.com/user-attachments/assets/ba620907-bf0d-42e1-9dc4-8f09e54d3cd4)

**Comment by tigpt** [comment]
![cookbook mascot color](https://github.com/user-attachments/assets/df8930b1-2f8a-4ead-a2f0-cabd3440e216)

**Comment by tigpt** [comment]
We have a logo, I'm going to close this topic
